### ISSUE TITLE
fail to build the examples

### ISSUE THREAD

**Issue by flankechen** [Rajawali/RajawaliVuforia#50]
New bird to android studio. When I sync and import example project to android studio, build action leads to an error like:
failed to resolve : 'org.rajawali3d.vuforia:rajawalivuforia:1.0.0-SNAPSHOT'

I understand that RajawaliVuforiaExamples -> RajawaliVuforia --> Rajawali

is gradle goes online to find the dependencies? could I add the jars and dependencies like before( things like in eclipse days)

Thanks!

**Comment by ToxicBakery** [comment]
If you call the uploadArchives task you can build local snapshots of each dependency. This is not very well setup yet and should be much better soon we when start pushing official builds.

**Comment by waniolka** [comment]
similar here, in my example executing uploadArchives returns fail and:
   > Could not find org.rajawali3d:rajawali:1.0.232-SNAPSHOT.

**Comment by MasDennis** [comment]
Hi,
Try uncommenting this line:
//maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
That should fix it. Mistakenly commented out. Will fix this.

**Comment by waniolka** [comment]
Thanks for quick answer. I've managed to build project. Now, what is the proper way of importing project? When I import RajawaliVuforiaExample still Android Studio Gradle returns error:
![screenshot](https://cloud.githubusercontent.com/assets/5065400/7856424/3246f860-0529-11e5-8a35-2e538b089c58.png)

**Comment by MasDennis** [comment]
RajawaliVuforiaExample shouldn't be looking for the Rajawali lib but the RajawaliVuforia lib in `mavenLocal()`. 
It should be looking for `org.rajawali3d.vuforia:rajawalivuforia:1.0.0-SNAPSHOT`. See https://github.com/Rajawali/RajawaliVuforia/blob/master/RajawaliVuforiaExample/app/build.gradle#L23

You should build RajawaliVuforia using this command:

`./gradlew clean assembleRelease uploadArchives`

This will build the local version of the library.

**Comment by joalbor1** [comment]
Hi! I'm having the same problem…

I uncomment the line:
`//maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }`
and build RajawaliVuforia project correctly with this:
`./gradlew clean assembleRelease uploadArchives`

But when I import just RajawaliVuforiaExample still Android Studio Gradle returns exactly the same error.

**Comment by waniolka** [comment]
Got solution. Change in RejawaliVuforiaExample build.gradle (this one in root not in app folder):
```
allprojects {
    repositories {
        jcenter()
        mavenLocal()
    }
}
```
to
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        mavenLocal()
    }
}
```
Sounds like big workaround byt in my case it worked, app compiled and run perfectly :)

**Comment by joalbor1** [comment]
Great!
My app compile and run perfectly, too :D

**Comment by MasDennis** [comment]
Good to hear guys. I'll update the files.

**Comment by MasDennis** [comment]
You're also welcome to submit a pull request for this :)

**Comment by MasDennis** [comment]
The fix has been pushed to master.

**Comment by shabbirsphinx** [comment]
Still get same erro

Failed to resolve: org.rajawali3d.vuforia:rajawalivuforia:1.0.0-SNAPSHOT
![build_gradle](https://cloud.githubusercontent.com/assets/2392859/9848282/4256bf5e-5afd-11e5-943f-385f721e2769.png)

**Comment by Boobaalan** [comment]
Cant able to rectify this error
![error](https://cloud.githubusercontent.com/assets/3184104/22009330/6af0a8b6-dca8-11e6-8f88-5000a4928e60.png)

**Comment by rkoshti** [comment]
@MasDennis It's not working for me in my latest android studio 

![2019-05-20_1445](https://user-images.githubusercontent.com/19707208/58010411-efd4c200-7b0d-11e9-9083-c5cabb14ae3b.png)

kindly help

**Comment by SinaMN75** [comment]
same problem here...
`ERROR: Failed to resolve: org.rajawali3d.vuforia:rajawalivuforia:1.0.0-SNAPSHOT
Show in Project Structure dialog
Affected Modules: app
`
<img width="593" alt="image" src="https://user-images.githubusercontent.com/34570827/58322876-861f2580-7e37-11e9-9fa8-37fa13159576.png">


<img width="552" alt="image" src="https://user-images.githubusercontent.com/34570827/58322853-71429200-7e37-11e9-98c0-31fc1c269453.png">

**Comment by rkoshti** [comment]
Seems Library is dead for vuforia

Admin is not interested in rajawali maintainance
